/**
 * Autogenerated by Frugal Compiler (0.0.1)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package foo;

import com.workiva.frugal.FScopeProvider;
import com.workiva.frugal.FSubscription;
import com.workiva.frugal.FProtocol;
import com.workiva.frugal.transport.FScopeTransport;
import org.apache.thrift.TException;
import org.apache.thrift.TApplicationException;
import org.apache.thrift.transport.TTransportException;
import org.apache.thrift.protocol.*;

import javax.annotation.Generated;




/**
 * And this is a scope docstring.
 */
@Generated(value = "Autogenerated by Frugal Compiler (0.0.1)", date = "2015-11-24")
public class FooPublisher {

	private static final String delimiter = ".";

	private FScopeProvider provider;
	private FScopeTransport transport;
	private FProtocol protocol;

	public FooPublisher(FScopeProvider provider) {
		this.provider = provider;
	}

	public void open() throws TException {
		FScopeProvider.Client client = provider.build();
		transport = client.getTransport();
		protocol = client.getProtocol();
		transport.open();
	}

	public void close() throws TException {
		transport.close();
	}

	/**
	 * This is an operation docstring.
	 */
	public void publishFoo(String baz, Thing req) throws TException {
		String op = "Foo";
		String prefix = String.format("foo.bar.%s.qux.", baz);
		String topic = String.format("%sFoo%s%s", prefix, delimiter, op);
		transport.lockTopic(topic);
		try {
			protocol.writeMessageBegin(new TMessage(op, TMessageType.CALL, 0));
			req.write(protocol);
			protocol.writeMessageEnd();
			transport.flush();
		} catch (TException e) {
			close();
			throw e;
		} finally {
			transport.unlockTopic();
		}
	}


	public void publishBar(String baz, Stuff req) throws TException {
		String op = "Bar";
		String prefix = String.format("foo.bar.%s.qux.", baz);
		String topic = String.format("%sFoo%s%s", prefix, delimiter, op);
		transport.lockTopic(topic);
		try {
			protocol.writeMessageBegin(new TMessage(op, TMessageType.CALL, 0));
			req.write(protocol);
			protocol.writeMessageEnd();
			transport.flush();
		} catch (TException e) {
			close();
			throw e;
		} finally {
			transport.unlockTopic();
		}
	}
}
