// Autogenerated by Frugal Compiler (2.20.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

import 'dart:typed_data' show Uint8List;
import 'package:thrift/thrift.dart' as thrift;
import 'package:include_vendor/include_vendor.dart' as t_include_vendor;
import 'package:some_vendored_place/vendor_namespace.dart' as t_vendor_namespace;
import 'package:excepts/excepts.dart' as t_excepts;

import 'dart:convert' show UTF8;

class IncludeVendorConstants {
  static final int reference_vendored_const = t_vendor_namespace.VendorNamespaceConstants.a_const;
}
