// Autogenerated by Frugal Compiler (1.8.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

library variety.src.f_its_an_enum;class ItsAnEnum {
  static const int FIRST = 2;
  static const int SECOND = 3;
  static const int THIRD = 4;

  static final Set<int> VALID_VALUES = new Set.from([
    FIRST,
    SECOND,
    THIRD,
  ]);

  static final Map<int, String> VALUES_TO_NAMES = {
    FIRST: 'FIRST',
    SECOND: 'SECOND',
    THIRD: 'THIRD',
  };
}
