/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library base;

export 'src/base_foo.dart' show BaseFoo;
export 'src/base_foo.dart' show BaseFooClient;
export 'src/base_foo.dart' show BaseFooProcessor;

export 'src/f_base_foo_service.dart' show FBaseFooClient;
