/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library base;

export 'src/base.dart' show Base;
export 'src/base.dart' show BaseClient;
export 'src/base.dart' show BaseProcessor;

export 'src/f_base_service.dart' show FBaseClient;
