/**
 * Autogenerated by Thrift Compiler (0.9.3-wk-3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library base;

export 'src/api_exception.dart' show api_exception;
export 'src/base_foo.dart' show BaseFoo;
export 'src/base_foo.dart' show BaseFooClient;
export 'src/base_foo.dart' show BaseFooProcessor;

export 'src/f_base_foo_service.dart' show FBaseFoo;
export 'src/f_base_foo_service.dart' show FBaseFooClient;
