// Autogenerated by Frugal Compiler (2.16.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

library enum_dart;

export 'src/f_testing_enums.dart' show testing_enums, serializetesting_enums, deserializetesting_enums;

