// Autogenerated by Frugal Compiler (2.16.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

import 'dart:typed_data' show Uint8List;
import 'package:thrift/thrift.dart' as thrift;
import 'package:actual_base_dart/actual_base_dart.dart' as t_actual_base_dart;

import 'dart:convert' show UTF8;

class ActualBaseDartConstants {
  static final int const_i32_from_base = 582;
}
