/**
 * Autogenerated by Frugal Compiler (0.0.1)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */



import com.workiva.frugal.FProvider;
import com.workiva.frugal.Transport;
import com.workiva.frugal.TransportFactory;
import com.workiva.frugal.Subscription;
import org.apache.thrift.TException;
import org.apache.thrift.protocol.*;
import org.apache.thrift.TApplicationException;

import org.apache.thrift.transport.TTransportException;

import org.apache.thrift.transport.TTransportFactory;

import javax.annotation.Generated;



/**
 * This docstring gets added to the generated code because it has
 * the @ sign.
 */
@Generated(value = "Autogenerated by Frugal Compiler (0.0.1)", date = "2016-1-6")
public class EventsPublisher {

	private static final String delimiter = ".";

	private FTransport transport;
	private FProtocol protocol;

	public EventsPublisher(FProvider provider) {
		FProvider.Client client = provider.build();
		this.transport = client.getTransport();
		this.protocol = client.getProtocol();
	}

	/**
	 * This is a docstring.
	 */
	public void publishEventCreated(String user, Event req) throws TException {
		String op = "EventCreated";
		String prefix = String.format("foo.%s.", user);
		String topic = String.format("%sEvents%s%s", prefix, delimiter, op);
        transport.lockTopic(topic);
        try {
            protocol.writeMessageBegin(new TMessage(op, TMessageType.CALL, 0));
            req.write(protocol);
            protocol.writeMessageEnd();
            transport.flush();
        } finally {
            transport.unlockTopic();
        }
	}
}
